### ISSUE TITLE
/flutter_unionad/lib/flutter_unionad_stream.dart:184行返回数据不为int

### ISSUE THREAD

**Issue by dalingng** [gstory0404/flutter_unionad#112]
### 描述
> 异常/需求具体描述
/flutter_unionad/lib/flutter_unionad_stream.dart:183行返回数据不为int为double
修改
/Users/dng/work/control-cluster/flutter_unionad/lib/flutter_unionad_callback.dart
中的OnRewardArrived和OnVerify就可以正常运行
### 设备版本
> '>=3.3.4 <4.0.0' 设备红米k60至尊版

### 插件版本
> 2.0.3

### 日志
> 详细的log日志或者截图录屏
```

```

**Comment by gstory0404** [comment]
![image](https://github.com/gstory0404/flutter_unionad/assets/17020178/62a1ac82-d66f-4a37-84c0-32683dd7f51c)
官方回传就int数值？怎么会出现double

**Comment by dalingng** [comment]
我也不清楚呀，我这边报错，我自己clone下来改了。

**Comment by dalingng** [comment]
报以下错误
```
E/flutter (28164): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'double' is not a subtype of type 'int'
E/flutter (28164): #0      FlutterUnionadStream.initAdStream.<anonymous closure> (package:flutter_unionad/flutter_unionad_stream.dart:182:42)
E/flutter (28164): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (28164): #2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
E/flutter (28164): #3      _DelayedData.perform (dart:async/stream_impl.dart:541:14)
E/flutter (28164): #4      _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
E/flutter (28164): #5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
E/flutter (28164): #6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (28164): #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by gstory0404** [comment]
已更新
