### ISSUE TITLE
激励视频 print 激励广告关闭后 onVerify会报错 

### ISSUE THREAD

**Issue by luyilafei** [gstory0404/flutter_unionad#113]
### 描述
激励视频点击关闭后 输出 激励广告关闭
到奖励这一步就会报错 提示webview 已销毁了
```
E/DMLibManager( 7483): aidl executeMultiProcessAppDownloadCallBack recycle res, materialMd5:-272102447fcff2422-4a0c-4057-b2b9-e5a3d81a8ee4u496263629980
E/DMLibManager( 7483): aidl executeMultiProcessAppDownloadCallBack recycle res, mListenerMap sizee:0
W/cr_AwContents( 7483): Application attempted to call on a destroyed WebView
W/cr_AwContents( 7483): java.lang.Throwable
W/cr_AwContents( 7483): 	at org.chromium.android_webview.AwContents.s(chromium-TrichromeWebViewGoogle6432.aab-stable-626106433:10)
W/cr_AwContents( 7483): 	at com.android.webview.chromium.WebViewChromium.removeJavascriptInterface(chromium-TrichromeWebViewGoogle6432.aab-stable-626106433:36)
W/cr_AwContents( 7483): 	at android.webkit.WebView.removeJavascriptInterface(WebView.java:1945)
W/cr_AwContents( 7483): 	at com.bytedance.sdk.openadsdk.core.se.n.nd(Unknown Source:307)
W/cr_AwContents( 7483): 	at com.bytedance.sdk.openadsdk.core.component.reward.endcard.jk.cr(Unknown Source:493)
W/cr_AwContents( 7483): 	at com.bytedance.sdk.openadsdk.core.component.reward.endcard.yj.cr(Unknown Source:422)
W/cr_AwContents( 7483): 	at com.bytedance.sdk.openadsdk.core.component.reward.f.yj.z(Unknown Source:302)
W/cr_AwContents( 7483): 	at com.bytedance.sdk.openadsdk.core.component.reward.activity.TTBaseVideoActivity.onDestroy(Unknown Source:1095)
W/cr_AwContents( 7483): 	at com.bytedance.sdk.openadsdk.core.component.reward.activity.TTRewardVideoActivity.onDestroy(Unknown Source:562)
W/cr_AwContents( 7483): 	at com.bytedance.pangle.activity.GenerateProxyActivity.onDestroy(Unknown Source:1049)
W/cr_AwContents( 7483): 	at android.app.Activity.performDestroy(Activity.java:8690)
W/cr_AwContents( 7483): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1438)
W/cr_AwContents( 7483): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5746)
W/cr_AwContents( 7483): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5792)
W/cr_AwContents( 7483): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
W/cr_AwContents( 7483): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
W/cr_AwContents( 7483): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
W/cr_AwContents( 7483): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
W/cr_AwContents( 7483): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
W/cr_AwContents( 7483): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/cr_AwContents( 7483): 	at android.os.Looper.loopOnce(Looper.java:240)
W/cr_AwContents( 7483): 	at android.os.Looper.loop(Looper.java:351)
W/cr_AwContents( 7483): 	at android.app.ActivityThread.main(ActivityThread.java:8423)
W/cr_AwContents( 7483): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents( 7483): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
W/cr_AwContents( 7483): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### 设备版本
 [√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.22631.3880], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] Connected device (4 available)

### 插件版本
2.0.3

**Comment by gstory0404** [comment]
SDK内部异常

**Comment by tankpanv** [comment]
> SDK内部异常

这个有办法可以解决吗，这种方式退出，我获取不到是否能返回奖励了

**Comment by gstory0404** [comment]
测试是有回调你那边没有？
