### ISSUE TITLE
FlutterUnionad.splashAdView报错flutter_unionad is not init

### ISSUE THREAD

**Issue by zanpen2000** [gstory0404/flutter_unionad#67]
#51 这个issue里也有提到，按照issue里面的，避免了混淆，并确保FlutterUnionad​.​register 返回值为true，问题依然出现。

### 下面是日志

```shell
I/flutter (21119): UnionAds: 正在初始化...
I/flutter (21119): Mob: 设置android平台通知配置
I/flutter (21119): Mob: 注册推送通知事件回调...
I/flutter (21119): Mob: 初始化完成
I/flutter (21119): Mob: MobPushSdk Version: 4.4.1
I/flutter (21119): Mob 设备ID :xxxxxxxxxx
I/flutter (21119): MobPush.onEvent:{"result":{"values":[{"nameValuePairs":{"from_tcp":false}}]},"action":3}
I/flutter (21119): 数据库地址：/data/user/0/com.zerone.sentence/app_flutter/sentence.db
I/flutter (21119): Mob: MobpushPlugin上传隐私协议授权: true
I/flutter (21119): Mob: SharesdkPlugin上传隐私协议授权: true
I/flutter (21119): 数据库打开: true
E/flutter (21119): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, flutter_unionad is not init, please check., null, java.lang.RuntimeException: flutter_unionad is not init, please check.
E/flutter (21119): 	at com.gstory.flutter_unionad.TTAdManagerHolder.get(TTAdManagerHolder.kt:18)
E/flutter (21119): 	at com.gstory.flutter_unionad.splashad.SplashAdView.<init>(SplashAdView.kt:60)
E/flutter (21119): 	at com.gstory.flutter_unionad.splashad.SplashAdViewFactory.create(SplashAdViewFactory.kt:17)
E/flutter (21119): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/flutter (21119): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (21119): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (21119): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (21119): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (21119): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (21119): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (21119): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (21119): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (21119): 	at android.os.Looper.loop(Looper.java:263)
E/flutter (21119): 	at android.app.ActivityThread.main(ActivityThread.java:8292)
E/flutter (21119): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21119): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/flutter (21119): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
E/flutter (21119): )
E/flutter (21119): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter (21119): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
E/flutter (21119): <asynchronous suspension>
E/flutter (21119): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146)
E/flutter (21119): <asynchronous suspension>
E/flutter (21119): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792)
E/flutter (21119): <asynchronous suspension>
E/flutter (21119): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:819)
E/flutter (21119): <asynchronous suspension>
E/flutter (21119): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:182)
E/flutter (21119): <asynchronous suspension>
E/flutter (21119): 
Debug service listening on ws://127.0.0.1:41953/y89L6huodck=/ws
E/初始化(21119): 成功
I/flutter (21119): UnionAds: 正在初始化...true
```

### 环境如下
```shell
$ flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.3.2, on Manjaro Linux 5.15.65-1-MANJARO, locale zh_CN.UTF-8)
    • Flutter version 3.3.2 on channel stable at /home/peng/dev-tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 天前), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/peng/dev-tools/Android/Sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/peng/dev-tools/Android/Sdk
    • Java binary at: /home/peng/dev-tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.1
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/peng/dev-tools/android-studio
    • Flutter plugin version 70.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /home/peng/dev-tools/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/peng/dev-tools/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /home/peng/dev-tools/idea-IU-212.5457.46
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • PCNM00 (mobile) • 9b844f5 • android-arm64  • Android 11 (API 30)
    • Linux (desktop) • linux   • linux-x64      • Manjaro Linux 5.15.65-1-MANJARO
    • Chrome (web)    • chrome  • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by zanpen2000** [comment]
是我的错，插件作者[说的](https://github.com/gstory0404/flutter_unionad/issues/51#issuecomment-1135324553)很对，需要确保register成功之后再调用开屏广告。
