### ISSUE TITLE
java.lang.SecurityException: Permission denial

### ISSUE THREAD

**Issue by lizhuoyuan** [gstory0404/flutter_unionad#81]
广告有初始化成功
开始加载视频激励广告时候有这样的报错:
D/TNCManager(32262): handleHostMapping, nomatch: api-access.pangolin-sdk-toutiao.com
W/System.err(32262): java.lang.SecurityException: Permission denial
W/System.err(32262): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2456)
W/System.err(32262): 	at android.os.Parcel.createException(Parcel.java:2440)
W/System.err(32262): 	at android.os.Parcel.readException(Parcel.java:2423)
W/System.err(32262): 	at android.os.Parcel.readException(Parcel.java:2365)
W/System.err(32262): 	at com.xiaomi.mirror.IMirrorAppService$Stub$Proxy.isWorking(IMirrorAppService.java:187)
W/System.err(32262): 	at com.xiaomi.mirror.MirrorManager.isWorking(MirrorManager.java:259)
W/System.err(32262): 	at com.bytedance.sdk.component.panglarmor.SoftDecTool.b(Native Method)
W/System.err(32262): 	at com.bytedance.dutexplorer.tmapcloak.obj_bytdance_call(Native Method)
W/System.err(32262): 	at com.bytedance.sdk.component.panglarmor.SoftDecTool.a(Unknown Source:15)
W/System.err(32262): 	at com.bytedance.sdk.component.panglarmor.SoftDecTool$2.run(Unknown Source:170)
W/System.err(32262): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(32262): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(32262): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err(32262): 	at android.os.Looper.loop(Looper.java:299)
W/System.err(32262): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ignored (32262): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

**Comment by lizhuoyuan** [comment]
目前发现可能是因为我监听的多了
